### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by wjurkowski** [wjurkowski/ONION#12]
related to #7 
The installation doesn't pick up neither CRAN nor Bioconductor

install.packages("/Users/jurkowsw/apps/ONION/builds/ONION_0.0.1.tar.gz", repos = NULL, type="source", dependencies='TRUE')
ERROR: dependencies ‘igraph’, ‘ChebiAPI’, ‘plyr’, ‘ReactomeAPI’, ‘RCurl’, ‘RJSONIO’, ‘XML’, ‘testthat’, ‘pls’, ‘corrplot’, ‘yacca’, ‘FRCC’, ‘httr’, ‘biomaRt’, ‘STRINGdb’, ‘BiocCheck’, ‘ChemmineR’, ‘CCA’, ‘gridExtra’, ‘mygene’ are not available for package ‘ONION’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/ONION’
Warning message:
In install.packages("/Users/jurkowsw/apps/ONION/builds/ONION_0.0.1.tar.gz",  :
  installation of package ‘/Users/jurkowsw/apps/ONION/builds/ONION_0.0.1.tar.gz’ had non-zero exit status

**Comment by wjurkowski** [comment]
similarly with the rest of the code currently stored in reactomeapi and chebiapi

> install.packages("/Users/jurkowsw/apps/reactomeapi/builds/ReactomeAPI_0.0.1.tar.gz", repos = NULL, type="source", dependencies='TRUE')

ERROR: dependencies ‘RCurl’, ‘XML’, ‘plyr’, ‘RJSONIO’ are not available for package ‘ReactomeAPI’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/ReactomeAPI’
Warning message:
In install.packages("/Users/jurkowsw/apps/reactomeapi/builds/ReactomeAPI_0.0.1.tar.gz",  :
  installation of package ‘/Users/jurkowsw/apps/reactomeapi/builds/ReactomeAPI_0.0.1.tar.gz’ had non-zero exit status

**Comment by koralgooll** [comment]
What is the operating system? MacOS is no supported. :)

**Comment by ewagajda** [comment]
it will work when package will be in cran or bioconductor
