### ISSUE TITLE
replacing previous import ‘pls::corrplot’ by ‘corrplot::corrplot’ when loading ‘ONION’ 

### ISSUE THREAD

**Issue by mariatraka** [wjurkowski/ONION#14]
I'm trying to lead ONION in R/3.3.0 and i get this msg. Can you check whether this is right and not causing any problems?

And another one:
Warning: replacing previous import ‘biomaRt::getGene’ by ‘mygene::getGene’ when loading ‘ONION’

**Comment by koralgooll** [comment]
For now it is OK. In future release I will clean it by using `importFrom(somepackage, somefunction)` intead of `import(somepackage)` in NAMESPACE file.

**Comment by koralgooll** [comment]
Done. I eliminated warnings caused by me.
