### ISSUE TITLE
error when running ONION  

### ISSUE THREAD

**Issue by wjurkowski** [wjurkowski/ONION#16]
> clasteredSmallMolecules <- ONION::clasterUsingOntology(pathToFile = paste(find.package("ONION"),"/example/nm-lipidomics.txt", sep = ""),
+ header = TRUE, ontologyRepresentatnion = ONION::firstExistsInReactomeChebiOntology)
Error: 'clasterUsingOntology' is not an exported object from 'namespace:ONION'

**Comment by koralgooll** [comment]
Fixed. Temporary name problem, now function is called `clusterUsingOntology()`.
