### ISSUE TITLE
no proteins found in reaction mapped with ONION::mapReactomePathwaysUnderOrganism

### ISSUE THREAD

**Issue by wjurkowski** [wjurkowski/ONION#20]
Some reactions are correctly mapped but the protein info is not extracted. See below:

> chebiIdsToReactomePathways
  chebiId  ensembleIds  reactomeIds  gensSymbols
1   15756 ENSG0000.... R-HSA-56.... IDI1, AC....
2   17268              R-HSA-14....             
3   28822              R-HSA-56....             
4   15541              R-HSA-75....             
5   15904              R-HSA-16.... 

I manually checked reaction R-HSA-1483226 and were able to find proteins in it which indicates that something went wrong with it.

**Comment by ewagajda** [comment]
UniProt database need to be added to find those terms

**Comment by koralgooll** [comment]
ONION makes search under UniProt2Reactome.txt.
