### ISSUE TITLE
function to read user defined class assignment

### ISSUE THREAD

**Issue by wjurkowski** [wjurkowski/ONION#30]
Assume definitions provided in a text file e.g.

Molecule ID         group
CHEBI:789                 1
CHEBI:12345             2
CHEBI:11111               1
...

**Comment by wjurkowski** [comment]
Use following format compatible with Mulea:

Group  Description Molecules
1 my_group_1 CHEBI:789,CHEBI:11111

**Comment by koralgooll** [comment]
Example of content of groups definition file:
Group	Description	Molecules
1	my_group_1	CHEBI:28875 CHEBI:73705
2	my_group_2	CHEBI:17268 CHEBI:35465 CHEBI:16196 CHEBI:36036 CHEBI:28661
3	my_group_3	CHEBI:15756 CHEBI:28716 CHEBI:36023 CHEBI:17351
4	my_group_A	CHEBI:17268
5	my_group_B	CHEBI:28842
6	my_group_C	CHEBI:28842 CHEBI:16196 CHEBI:32425

**Comment by koralgooll** [comment]
Method to read user defined data is created and ready to use:
gmtGroupsFilePath <- paste(find.package("ONION"),"/example/nm-groups.txt", sep = "")
groups <- ONION::groupUsingUserDefinition(pathToFileWithGroupDefinition = gmtGroupsFilePath)
