### ISSUE TITLE
spelling mistake in one of the functions

### ISSUE THREAD

**Issue by ewagajda** [wjurkowski/ONION#33]
In function 
chebiIdsToReactomePathways <- ONION::mapReactomePathwaysUnderOrganism(chebiOntologyIds = mergedSmallMolecules, organismTaxonomyId = '9606')

two columns have spelling mistake in headers, it should be:
genesSymbols instead of gensSymbols,
genesSymbolsFromUniProt instead of gensSymbolsFromUniProt

**Comment by koralgooll** [comment]
Additionally is one spelling mistake in getStringNeighbours:
stringGensSymbols -> stringGenesSymbols

**Comment by koralgooll** [comment]
Fixed.
