### ISSUE TITLE
clusterWithCutoff assigns molecules to multiple clusters

### ISSUE THREAD

**Issue by Nuanda** [wjurkowski/ONION#42]
According to the `clusterWithCutoff` documentation (in the source code comments) no molecule should be assigned to more than one cluster. For instance, the library I attach has 20 molecules, which get clustered into several clusters, which has, in total, 21 molecules. A single molecule (I think it's the perfluorooctanoic acid) is assigned to two different clusters. This is for the cutoff value of 0.5.

[smaller_library_example.sdf.gz](https://github.com/wjurkowski/ONION/files/463988/smaller_library_example.sdf.gz)

I also had a 100 molecule library and got clusters which, in total, had 121 molecules (21 molecule repetitions) - so this is not incidental.

**Comment by wjurkowski** [comment]
maybe the comments are out of date, in principle we aim at having
overlapping cluster

2016-09-09 14:09 GMT+01:00 Tomasz Gubała <notifications@github.com>:

**Comment by Nuanda** [comment]
I see. Thanks.
