### ISSUE TITLE
build doesn't work

### ISSUE THREAD

**Issue by wjurkowski** [wjurkowski/ONION#6]
On linux:
> install.packages("/usr/users/ga002/jurkowsw/apps/ONION/builds/binaryPackages/ONION_0.0.1.zip", repos = NULL)
Error in rawToChar(block[seq_len(ns)]) : 
  embedded nul in string: 'PK\003\004\n\0\0\0\0\0\006\xbe-H\0\0\0\0\0\0\0\0\0\0\0\0\006\0\0\0ONION/PK\003\004\024\0\002\0\b\0\xf1\xbd-H\033\t\x94\xc9\xd8\001\0\0\xc3\002\0\0\021\0\0\0ONION/DESCRIPTIONE\x92]o\x9b0\024\x86\xef\x91\xf8\017GÚ­A\t'
Warning message:
In install.packages("/usr/users/ga002/jurkowsw/apps/ONION/builds/binaryPackages/ONION_0.0.1.zip",  :
  installation of package â had non-zero exit status

The same on my mac:
> install.packages("/Users/jurkowsw/Downloads/ONION_0.0.1.zip", repos = NULL, type = 'source')
Installing package into ‘/Users/jurkowsw/Library/R/3.2/library’
(as ‘lib’ is unspecified)
Error in rawToChar(block[seq_len(ns)]) : 
  embedded nul in string: 'PK\003\004\n\0\0\0\0\0\006\xbe-H\0\0\0\0\0\0\0\0\0\0\0\0\006\0\0\0ONION/PK\003\004\024\0\002\0\b\0\xf1\xbd-H\033\t\x94\xc9\xd8\001\0\0\xc3\002\0\0\021\0\0\0ONION/DESCRIPTIONE\x92]o\x9b0\024\x86\xef\x91\xf8\017GڭA\t'
Warning in install.packages :
  installation of package ‘/Users/jurkowsw/Downloads/ONION_0.0.1.zip’ had non-zero exit status

**Comment by koralgooll** [comment]
Please try to do the same with source package. Last one was binary package installed in source package way. This is link to download it: https://github.com/wjurkowski/ONION/blob/master/builds/sourcePackages/ONION_0.0.1.tar.gz?raw=true

From R documentation: "Possible values of type are (currently) "source", "mac.binary", "mac.binary.mavericks" and "win.binary": the appropriate binary type where supported can also be selected as "binary"."

So according to that my command to install source package looks like that: install.packages('C:/Users/Koralgooll/Downloads/ONION_0.0.1.tar.gz', repos = NULL, type = "source");
library('ONION')

**Comment by wjurkowski** [comment]
Ok, it seems to work. I assume that the binary package is of the win.binary type? Is it correct? Could you  provide readme in the builds dir?

**Comment by wjurkowski** [comment]
No it doesn't. After I installed the dependencies and continue with installation I get:

> install.packages("/Users/jurkowsw/Downloads/ONION_0.0.1.tar.gz", repos = NULL, type = 'source')
Installing package into ‘/Users/jurkowsw/Library/R/3.2/library’
(as ‘lib’ is unspecified)
* installing *source* package ‘ONION’ ...
** R
** preparing package for lazy loading
Warning: replacing previous import by ‘corrplot::corrplot’ when loading ‘ONION’
Note: the specification for S3 class “AsIs” in package ‘RJSONIO’ seems equivalent to one from package ‘BiocGenerics’: not turning on duplicate class definitions for this class.
Error : .onLoad failed in loadNamespace() for 'ChemmineOB', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Users/jurkowsw/Library/R/3.2/library/ChemmineOB/libs/ChemmineOB.so':
  dlopen(/Users/jurkowsw/Library/R/3.2/library/ChemmineOB/libs/ChemmineOB.so, 10): Library not loaded: /usr/local/lib/libopenbabel.4.dylib
  Referenced from: /Users/jurkowsw/Library/R/3.2/library/ChemmineOB/libs/ChemmineOB.so
  Reason: image not found
ERROR: lazy loading failed for package ‘ONION’
* removing ‘/Users/jurkowsw/Library/R/3.2/library/ONION’

**Comment by wjurkowski** [comment]
Build works fine after installing OpenBabel (stand alone for Mac OS)

**Comment by wjurkowski** [comment]
These warnings remain

Warning: replacing previous import by ‘corrplot::corrplot’ when loading ‘ONION’
Note: the specification for S3 class “AsIs” in package ‘RJSONIO’ seems equivalent to one from package ‘BiocGenerics’: not turning on duplicate class definitions for this class.
Note: the specification for class “RSWIGStruct” in package ‘ChemmineOB’ seems equivalent to one from package ‘ChemmineR’: not turning on duplicate class definitions for this class.

**Comment by koralgooll** [comment]
Warnings will be fixed in #14 .
